[project]
name = "jablonski"
authors = [
  { name = "Tomas Di Napoli", email = "tomas.dina98@gmail.com" },
  { name = "Hernan E. Grecco", email = "hernan.grecco@gmail.com" },
]
description = "Write and simulate ODE systems to describe the transitions in spectroscopic molecular systems."
version = "0.2.0"
requires-python = ">=3.12"
keywords = []
license = "BSD-3-Clause"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Topic :: Software Development :: Libraries",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering",
  "Programming Language :: Python :: 3",
]
dependencies = ["poincare >= 1.1.1"]

[project.urls]
homepage = "https://github.com/dyscolab/jablonski"
issues = "https://github.com/dyscolab/jablonski/issues"
documentation = "https://dyscolab.github.io/jablonski"

[build-system]
requires = ["uv_build>=0.9,<0.10"]
build-backend = "uv_build"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
extend-select = ["I"]

[tool.pyright]
typeCheckingMode = "standard"
venv = "test"
venvPath = ".pixi/envs/"

[tool.pyrefly]
python-interpreter-path = ".pixi/envs/default/bin/python"
project-excludes = [".pixi", "**/__pycache__"]

[tool.ty.environment]
python = ".pixi/envs/default"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "win-64"]
preview = ["pixi-build"]

[tool.pixi.package.build]
backend = { name = "pixi-build-python", version = "*" }
config = { ignore-pypi-mapping = false }                # Enable automatic PyPI-to-conda mapping

[tool.pixi.package.host-dependencies]
uv-build = "*"


[tool.pixi.environments]
default = ["test", "py312"]
lint = { features = ["lint"], no-default-feature = true }
build = { features = ["build"], no-default-feature = true }
test-py312 = ["test", "py312"]
test-py313 = ["test", "py313"]
test-py314 = ["test", "py314"]

[tool.pixi.dependencies]
jablonski = { path = "." }

[tool.pixi.feature.lint.dependencies]
pre-commit = "*"
pre-commit-hooks = "*"
taplo = "*"
ruff = "*"
mdformat = "*"
mdformat-ruff = "*"
pyright = "*"

[tool.pixi.feature.lint.tasks]
pre-commit-install = "pre-commit install"
lint = "pre-commit run"

[tool.pixi.feature.build.dependencies]
uv = "*"
python = "*"


[tool.pixi.feature.build.tasks]
_build = "uv build"
_publish = "uv publish"


[tool.pixi.feature.test.dependencies]
matplotlib = "*"
pytest = "*"
pooch = "*"

[tool.pixi.feature.test.tasks]
test = "pytest --doctest-modules"

[tool.pixi.feature]
py312.dependencies = { python = "3.12.*" }
py313.dependencies = { python = "3.13.*" }
py314.dependencies = { python = "3.14.*" }
